### ISSUE TITLE
Obtain the database port in a dynamic fashion.

### ISSUE THREAD

**Issue by TobyHFerguson** [Redislabs-Solution-Architects/cloud-run-for-anthos-labs#2]
At the moment the redis database's port is edited into the services.yaml file using a sed script and some kubectl get stuff.

What I want to do is to simply reference the dynamically created port number.

See [here for ideas](https://github.com/RoeyPrat/GitopsWithRedisEnterpriseOperator/blob/master/workloads/app_and_database.yaml)

**Comment by TobyHFerguson** [comment]
This [moodle reference](https://redislabs.moodle.school/mod/page/view.php?id=763&forceview=1) shows how to obtain the port from the database secret:

![image](https://user-images.githubusercontent.com/6525189/93475167-2a3ea280-f8ad-11ea-835e-a183e45610fa.png)

**Comment by TobyHFerguson** [comment]
I need more than the port, I need the hostname. [This article](https://stackoverflow.com/questions/40889743/string-operation-on-env-variables-on-kubernetes) showed me how I can use the `$()` construct to concatenate strings. I think the following might work:

```
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: redis-enterprise-database
                key: port
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: redis-enterprise-database
                key: service_name              
          - name: REDIS_ADDR
            value: "$(REDIS_HOST):$(REDIS_PORT)"
```
